controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

cgv:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/cgv.html.twig